# Section 1

To display high level overview

In [2]:
import pandas as pd
file_path = '/content/business_analytics_lab_CT1_data.csv'
df=pd.read_csv(file_path)
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    10100 non-null  object
 1   Customer_Name     10100 non-null  object
 2   Purchase_Date     10100 non-null  object
 3   Product_Category  9593 non-null   object
 4   Quantity          10100 non-null  int64
 5   Unit_Price        9089 non-null   float64
 6   Contact_Location  10100 non-null  object
 7   Membership_Level  10100 non-null  object
 8   Discount_Applied  10100 non-null  bool
 9   Rating            8431 non-null   float64
dtypes: bool(1), float64(2), int64(1), object(6)
memory usage: 720.1+ KB

None

Identifying columns with null values

In [3]:
df.isnull().sum()

Transaction_ID         0
Customer_Name          0
Purchase_Date          0
Product_Category     507
Quantity               0
Unit_Price          1011
Contact_Location       0
Membership_Level       0
Discount_Applied       0
Rating              1669
dtype: int64

Showing top 3 rows

In [4]:
df.head(3)

,Transaction_ID,Customer_Name,Purchase_Date,Product_Category,Quantity,Unit_Price,Contact_Location,Membership_Level,Discount_Applied,Rating
0,TXN-00000,diana Prince,Oct-10-2023,electronics,36,NaN,"Toronto, CA",Basic,True,3.0
1,TXN-00001,alice smith,2023/05/12,Electronics,35,485.430092,"New York, NY",Gold,True,4.0
2,TXN-00002,Edward Norton,2023/05/12,electronics,28,27.317580,"Toronto, CA",Basic,True,3.0

Display the mean, median and standard deviation of column ‘Rating’

In [5]:
df['Rating'].describe()

count    8431.000000
mean        2.982209
std         1.409733
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Rating, dtype: float64

Identifying physical shape

In [9]:
display(df.shape)

(10100, 10)

Finding duplicated values

In [15]:
df_2=df.copy()

display(df_2.shape)

(10100, 10)

Removing

In [18]:
df_2.drop_duplicates(inplace=True)
display(df_2.shape)

(10000, 10)

# Section 2

Imputation

In [24]:
import pandas as pd
file_path = '/content/business_analytics_lab_CT1_data.csv'
df=pd.read_csv(file_path)
df_3=df.copy()
df_3['Unit_Price']=df_3['Unit_Price'].fillna(df_3['Unit_Price'].mean())
df_3.isnull().sum()

Transaction_ID         0
Customer_Name          0
Purchase_Date          0
Product_Category     507
Quantity               0
Unit_Price             0
Contact_Location       0
Membership_Level       0
Discount_Applied       0
Rating              1669
dtype: int64

Logical Validation

Finding negative numbers in 'Quantity'

In [29]:
df4=df.copy()
negative_quantity_rows = df4[df4['Quantity'] < 0]


num_negative_quantities = len(negative_quantity_rows)

print(f"Number of rows with Quantity less than zero: {num_negative_quantities}")

Number of rows with Quantity less than zero: 940

Replacing with '0'

In [30]:

df4.loc[df4['Quantity'] < 0, 'Quantity'] = 0


num_negative_quantities_after = len(df4[df4['Quantity'] < 0])
print(f"Number of rows with Quantity less than zero after replacement: {num_negative_quantities_after}")


display(df_3['Quantity'].describe())

Number of rows with Quantity less than zero after replacement: 0

count    10100.000000
mean        22.529109
std         15.722279
min          0.000000
25%          8.000000
50%         22.000000
75%         36.000000
max         50.000000
Name: Quantity, dtype: float64

Categorical Cleaning

In [36]:
df_5=df4.copy()
df['Rating'].isnull().sum()

np.int64(1669)

In [38]:

df_5['Rating']= df_5['Rating'].fillna('Not Rated')
df_5['Rating'].isnull().sum()

np.int64(0)

# Section 3

Case Normalisation

In [40]:

print("Product_Category unique values before normalization:")
display(df_5['Product_Category'].value_counts())

df_5['Product_Category'] = df_5['Product_Category'].str.lower()

print("\nProduct_Category unique values after normalization:")
display(df_5['Product_Category'].value_counts())

Product_Category unique values before normalization:

Product_Category
Furniture        1680
  furniture      1622
ELECTRONICS      1600
Electronics      1590
FURNITURE        1577
electronics      1524
Name: count, dtype: int64

Product_Category unique values after normalization:

Product_Category
electronics      4714
furniture        3257
  furniture      1622
Name: count, dtype: int64

Trimming

In [41]:
print("Customer_Name unique values before trimming:")
display(df_5['Customer_Name'].value_counts().head())

df_5['Customer_Name'] = df_5['Customer_Name'].str.strip()

print("\nCustomer_Name unique values after trimming:")
display(df_5['Customer_Name'].value_counts().head())

Customer_Name unique values before trimming:

Customer_Name
BOB JONES           2078
Charlie Brown       2070
   Edward Norton    2011
 alice smith        1973
diana Prince        1968
Name: count, dtype: int64

Customer_Name unique values after trimming:

Customer_Name
BOB JONES        2078
Charlie Brown    2070
Edward Norton    2011
alice smith      1973
diana Prince     1968
Name: count, dtype: int64

Standardization

In [43]:
print("Unique 'State_Code' values (extracted from Contact_Location) before standardization:")
df_5['State_Code'] = df_5['Contact_Location'].apply(lambda x: x.split(', ')[-1] if ', ' in x else '')
display(df_5['State_Code'].value_counts())


df_5['State_Code'] = df_5['State_Code'].str.upper()

print("\nUnique 'State_Code' values after standardization to uppercase:")
display(df_5['State_Code'].value_counts())

Unique 'State_Code' values (extracted from Contact_Location) before standardization:

State_Code
UK    2637
CA    2556
JP    2457
NY    2450
Name: count, dtype: int64

Unique 'State_Code' values after standardization to uppercase:

State_Code
UK    2637
CA    2556
JP    2457
NY    2450
Name: count, dtype: int64

Final health Check

In [44]:
df.describe()

           Quantity   Unit_Price       Rating
count  10100.000000  9089.000000  8431.000000
mean      22.242079   255.802888     2.982209
std       16.159031   141.136009     1.409733
min       -5.000000    10.017821     1.000000
25%        8.000000   135.161240     2.000000
50%       22.000000   255.512072     3.000000
75%       36.000000   379.145522     4.000000
max       50.000000   499.952664     5.000000

In [45]:
df.isnull().sum()

Transaction_ID         0
Customer_Name          0
Purchase_Date          0
Product_Category     507
Quantity               0
Unit_Price          1011
Contact_Location       0
Membership_Level       0
Discount_Applied       0
Rating              1669
dtype: int64

These are neccessary to understand the basic workflows of python.